// Generated by jextract

package io.h3ca.forgemind.core.internal.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;

public class forgemind_h extends forgemind_h$shared {

    forgemind_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());


    private static class computeGradients {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            forgemind_h.C_POINTER,
            forgemind_h.C_POINTER,
            forgemind_h.C_POINTER,
            forgemind_h.C_POINTER,
            forgemind_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("computeGradients");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void computeGradients(int *padding, Tensor *delta, Tensor *input, Tensor *biasGradient, Tensor *weightsGradient)
     * }
     */
    public static FunctionDescriptor computeGradients$descriptor() {
        return computeGradients.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void computeGradients(int *padding, Tensor *delta, Tensor *input, Tensor *biasGradient, Tensor *weightsGradient)
     * }
     */
    public static MethodHandle computeGradients$handle() {
        return computeGradients.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void computeGradients(int *padding, Tensor *delta, Tensor *input, Tensor *biasGradient, Tensor *weightsGradient)
     * }
     */
    public static MemorySegment computeGradients$address() {
        return computeGradients.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void computeGradients(int *padding, Tensor *delta, Tensor *input, Tensor *biasGradient, Tensor *weightsGradient)
     * }
     */
    public static void computeGradients(MemorySegment padding, MemorySegment delta, MemorySegment input, MemorySegment biasGradient, MemorySegment weightsGradient) {
        var mh$ = computeGradients.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("computeGradients", padding, delta, input, biasGradient, weightsGradient);
            }
            mh$.invokeExact(padding, delta, input, biasGradient, weightsGradient);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

